In [8]:
import numpy as np

In [9]:
# 1. Initialize an empty array with size 2X2
empty_array = np.empty((2, 2))
print("Empty array (2x2):\n", empty_array)

Empty array (2x2):
 [[4.82923755e-310 0.00000000e+000]
 [9.04115220e+271 1.02124020e+277]]


In [10]:
# 2. Initialize an all one array with size 4X2
ones_array = np.ones((4, 2))
print("All ones array (4x2):\n", ones_array)

All ones array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [11]:
# 3. Return a new array of given shape and type, filled with fill value
fill_value = 7
filled_array = np.full((3, 3), fill_value)
print("Array filled with value 7 (3x3):\n", filled_array)

Array filled with value 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [12]:
# 4. Return a new array of zeros with same shape and type as a given array
given_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(given_array)
print("Zeros array with same shape as given array:\n", zeros_like_array)


Zeros array with same shape as given array:
 [[0 0 0]
 [0 0 0]]


In [ ]:
# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("Ones array with same shape as given array:\n", ones_like_array)

Ones array with same shape as given array:
 [[1 1 1]
 [1 1 1]]


In [ ]:
# 6. Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("Numpy array from list:\n", numpy_array)

Numpy array from list:
 [1 2 3 4]


In [ ]:
# 1. Create an array with values ranging from 10 to 49
array_10_to_49 = np.arange(10, 50)
print("Array with values from 10 to 49:\n", array_10_to_49)


Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# 2. Create a 3X3 matrix with values ranging from 0 to 8
matrix_0_to_8 = np.arange(9).reshape(3, 3)
print("3x3 matrix with values from 0 to 8:\n", matrix_0_to_8)

3x3 matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 3. Create a 3X3 identity matrix
identity_matrix = np.eye(3)
print("3x3 identity matrix:\n", identity_matrix)


3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
# 4. Create a random array of size 30 and find the mean of the array
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random array of size 30:\n", random_array)
print("Mean of the random array:\n", mean_value)

Random array of size 30:
 [0.82757481 0.52834092 0.48706618 0.49774071 0.0791337  0.8041691
 0.55029076 0.94783018 0.58009901 0.63031834 0.40808264 0.82617309
 0.29525761 0.18881406 0.02909684 0.14931149 0.69087973 0.1352278
 0.18916322 0.27104093 0.06617442 0.89253128 0.70727565 0.3241676
 0.76852913 0.17685061 0.25612265 0.03700534 0.37767196 0.41933879]
Mean of the random array:
 0.4380426192453805


In [14]:
# 5. Create a 10X10 array with random values and find the minimum and maximum values
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("10x10 array with random values:\n", random_10x10)
print("Minimum value:\n", min_value)
print("Maximum value:\n", max_value)


10x10 array with random values:
 [[0.26175639 0.79196637 0.24015603 0.77184107 0.60351584 0.70034679
  0.06161668 0.75162227 0.278049   0.32575351]
 [0.84589888 0.92570291 0.70907047 0.85570576 0.38300792 0.87930747
  0.72844713 0.01925585 0.62414698 0.7795899 ]
 [0.07709884 0.12965101 0.81848742 0.63997656 0.57253001 0.21755294
  0.55019098 0.37804433 0.45212821 0.9799857 ]
 [0.59913771 0.51896156 0.55765788 0.25991134 0.95136962 0.94692744
  0.93759123 0.29017553 0.5358533  0.46750418]
 [0.01566359 0.13523828 0.43307583 0.01094401 0.29888854 0.05247918
  0.7137632  0.92933636 0.69206055 0.25261441]
 [0.11326049 0.06794504 0.58576701 0.9644189  0.06363047 0.52717647
  0.54226726 0.17613304 0.86650308 0.54580305]
 [0.27459766 0.11432968 0.75506696 0.99840937 0.96723689 0.5094635
  0.03208981 0.83820837 0.35396507 0.50942485]
 [0.52230511 0.86353957 0.48740905 0.45951515 0.55582716 0.58265166
  0.61696692 0.97512415 0.41895867 0.00757769]
 [0.77668267 0.01862972 0.08034111 0.08962401 0.

In [ ]:
# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("Zero array with 5th element replaced by 1:\n", zero_array)


Zero array with 5th element replaced by 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = [1, 2, 0, 0, 4, 0]
reversed_arr = arr[::-1]
print("Reversed array:\n", reversed_arr)


Reversed array:
 [0, 4, 0, 0, 2, 1]


In [ ]:
# 8. Create a 2d array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("2D array with 1 on border and 0 inside:\n", border_array)


2D array with 1 on border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# 9. Create a 8X8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 checkerboard pattern:\n", checkerboard)


8x8 checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("Addition of x and y:\n", add_xy)

Addition of x and y:
 [[ 6  8]
 [10 13]]
Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]
Multiplication of x with 2:
 [[ 2  4]
 [ 6 10]]
Square of each element in x:
 [[ 1  4]
 [ 9 25]]
Dot product of v and w:
 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]
Concatenation of x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along column:
 [[ 9 10]
 [11 12]]
Error in concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [ ]:
# 2. Subtract the two arrays
subtract_xy = x - y
print("Subtraction of x and y:\n", subtract_xy)

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]


In [ ]:
# 3. Multiply the array with any integers of your choice
multiply_x = x * 2
print("Multiplication of x with 2:\n", multiply_x)


Multiplication of x with 2:
 [[ 2  4]
 [ 6 10]]


In [ ]:
# 4. Find the square of each element of the array
square_x = np.square(x)
print("Square of each element in x:\n", square_x)


Square of each element in x:
 [[ 1  4]
 [ 9 25]]


In [ ]:
# 5. Find the dot product between: v and w; x and v; x and y
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("Dot product of v and w:\n", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)

Dot product of v and w:
 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


In [ ]:
# 6. Concatenate x and y along row and Concatenate v and w along column
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.vstack((v, w))
print("Concatenation of x and y along row:\n", concat_xy_row)
print("Concatenation of v and w along column:\n", concat_vw_col)


Concatenation of x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along column:
 [[ 9 10]
 [11 12]]


In [ ]:
# 7. Concatenate x and v; if you get an error, observe and explain why did you get the error?
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("Concatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("Error in concatenating x and v:", e)

Error in concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [16]:

A = np.array([[3, 4], [7, 8]])
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A^-1:\n", identity_matrix)


A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [17]:
B = np.array([[5, 3], [2, 1]])
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)


AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]


In [18]:
AB_transpose = np.transpose(AB)
B_transpose = np.transpose(B)
A_transpose = np.transpose(A)
BT_AT = np.dot(B_transpose, A_transpose)
print("(AB)^T:\n", AB_transpose)
print("B^T * A^T:\n", BT_AT)

(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
